syntax = "proto3";

import "google/protobuf/timestamp.proto";

package event;

option go_package = "./;internalgrpc";

service EventService {
    rpc CreateEvent (CreateEventRequest) returns (EventResponse);
    rpc UpdateEvent (EventRequest) returns (EventResponse);
    rpc DeleteEvent (EventRequest) returns (EventResponse);
    rpc SelectEventByDay (SelectEventRequest) returns (ArrayEventResponse);
    rpc SelectEventByWeek (SelectEventRequest) returns (ArrayEventResponse);
    rpc SelectEventByMonth (SelectEventRequest) returns (ArrayEventResponse);
}

message Event {
    string id = 1;
    string title = 2;
    string description = 3;
    google.protobuf.Timestamp start_time = 4;
    google.protobuf.Timestamp end_time = 5;
    string user_id = 6;
}

message CreateEventRequest {
    Event event = 1;
}

message EventRequest {
    string id = 1;
}

message SelectEventRequest {
    google.protobuf.Timestamp date = 1;
    string range = 2;
}

message EventResponse {
    Event event = 1;
}

message ArrayEventResponse {
  repeated Event events = 1;
}
